### ISSUE TITLE
Library causing Warning (MSB3277) - Found conflict between different versions of the same assembly

### ISSUE THREAD

**Issue by FilledStacks** [autofac/Autofac.Extras.MvvmCross#10] opened 2017-09-28 08:41 UTC
The latest nuget package still depends on MvvmCross v4 and using any MvvmCross v5 project will produce this warning. I wanted to take it up to do the upgrade and submit a pull request but I'm having some trouble upgrading any of the packages due to other lower versions being used in the code.

**Nuget package Version:** 4.0.2

**Reproduction steps:** Install latest Nuget package into a Mvvmcross project that is using v5 and the warning will appear when building.

You could give me some pointers on upgrading the project if you don't have time and I'll do it for you and submit a pull request.

**Comment by tillig** [comment] 2017-09-28 12:16
Did you track down which library is considered duplicate?

**Comment by FilledStacks** [comment] 2017-09-28 12:24
Yes, sorry I thought I put that in there. It's MvvmCross.Platform

**Comment by tillig** [comment] 2017-09-28 12:27
Do you have a direct project reference on that?

**Comment by FilledStacks** [comment] 2017-09-28 12:28
It's installed with the MvvmCross starter pack so it's in the packages. But I didn't install it as a separate nuget package.

**Comment by tillig** [comment] 2017-09-28 12:34
Reason I ask is the message implies you somehow have two versions of that library referenced. I usually see that when two different transitive dependencies require it but the project itself doesn't directly specify a package reference. Usually these issues are solved by directly referencing the version you want.

**Comment by FilledStacks** [comment] 2017-09-28 12:39
I would assume so too, but I do not have two versions referenced. I did check the code of this project however and saw that the latest version of this project depends on V4. The build process picked that up and then has to make a decision (it chose the right one, latest) and still works fine. But the warning persists. I only have v5.1.1 of MvvmCross installed (checked all packages, app config and project files). This appears with a new project as well.

Any idea how I can get it away, I like the build logs to be clean.

**Comment by tillig** [comment] 2017-09-28 12:51
How did your build process find v4? If it's not in your packages, where did it find the old version?

I'm not trying to put off your issue, I want to make sure the breaking change of requiring the new version in the Autofac. MvvmCross package is truly required before we go there. Given these issues can be caused by different things, it's important to understand the exact cause here. I'm trying to ferret out where it's getting the second/older version to cause the conflict in the first place. If it couldn't find two versions, it wouldn't be giving you the warning.

**Comment by FilledStacks** [comment] 2017-09-28 12:59
I completely understand your concern. Here is what lead me to this. In the detailed build log I found the following:

 There was a conflict between "MvvmCross.Platform, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null" and "MvvmCross.Platform, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null".
        "MvvmCross.Platform, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null" was chosen because it was primary and "MvvmCross.Platform, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" was not.
        **References which depend on "MvvmCross.Platform, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null**" [ ..... (All references that are being good) ]
...
...
...
References which depend on "MvvmCross.Platform, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" []. <--- No reference in my code
            /Users/danemackier/MyFiles/Work/Clients/source/AppName/packages/Autofac.Extras.MvvmCross.4.0.2/lib/portable45-net45+win8+wpa81/Autofac.Extras.MvvmCross.dll
              **Project file item includes which caused reference "/Users/danemackier/MyFiles/Work/Clients/source/AppName/packages/Autofac.Extras.MvvmCross.4.0.2/lib/portable45-net45+win8+wpa81/Autofac.Extras.MvvmCross.dll"**.
                /Users/danemackier/MyFiles/Work/Clients/source/AppName/packages/Autofac.Extras.MvvmCross.4.0.2/lib/portable45-net45+win8+wpa81/Autofac.Extras.MvvmCross.dll

I hope this helps. Maybe I'm miss understanding what this means, if so I apologize. Please correct me if I'm wrong.

**Comment by tillig** [comment] 2017-09-28 13:13
Is there a binding redirect in your app.config to point everything to the later MvvmCross?

**Comment by FilledStacks** [comment] 2017-09-28 13:21
No I don't have one in any of the projects (Android, iOS or Shared PCL)

But as a note Autofac does have a binding redirect in the PCL.

```
 <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.6.1.0" newVersion="4.6.1.0" />
 </dependentAssembly>
```

**Comment by tillig** [comment] 2017-09-28 14:06
Try adding one for the MvvmCross assembly, see if the warning in that instance goes away.

**Comment by FilledStacks** [comment] 2017-09-29 12:56
I added for v4.0.0 and and then tried for v5.1.0 it didn't go away. I'll ignore this message for now. But the goal is to get it away. Will come back after going live and let you know if I found anything.

**Comment by tillig** [comment] 2017-09-29 18:00
I'll have to get cross platform tooling installed to see if I can repro this. I won't lie, it may not be super soon. So many issues, so little time. Basically I just need to see if I can repro the thing in a brand new, totally empty MvvmCross project as described in the initial issue notes.

**Comment by tillig** [comment] 2017-09-29 18:57
- Which target framework(s) are you using for the affected project?
- Are you using Visual Studio or Xamarin Studio?

**Comment by FilledStacks** [comment] 2017-10-26 15:00
Sorry for the long gap, I understand you're busy. 

Visual Studio for Mac and Windows is where I see the error. 

Target version is set to Auto, so latest. Currently 26 on my machine for Android.

**Comment by tillig** [comment] 2017-10-26 15:14
Maybe I am misunderstanding how to repro this. When I was asking about target framework, I'm talking about this:

![Select target framework for project](https://user-images.githubusercontent.com/1156571/32060803-b453298e-ba24-11e7-8f3f-0d44cb4a43e8.PNG)

There's really not a target framework "Auto" - you have to target some platform. If it's .NET Standard / .NET Core, it'll look more like this:

![.NET Core targets](https://user-images.githubusercontent.com/1156571/32060895-fc185906-ba24-11e7-8bd9-17f62a4721b9.PNG)

**Can you give me very specific instructions on how to repro this so I'm sure I'm seeing the same thing?** Not to be pedantic, just since I _don't use MvvmCross_ and I _didn't write this integration_ it might seem like I have context that I really don't. This was sort of a drive-by contribution that occasionally the original committers revisit but not too often.

So, like...

1. File => New => Project...
2. Select Visual C# => Cross-Platform => Cross Platform App (Xamarin)
3. ...

(or whatever - I don't know what the actual project type is that you're using, etc.)

Thanks!

**Comment by tillig** [comment] 2018-02-05 18:35
It's been a while so I'm going to go ahead and close this issue. If we need to reopen, that's fine, but I'll need very specific repro instructions so we know what actions to take.

**Closed as completed by tillig** 2018-02-05 18:35 UTC
Labels: question
